ci translation-diff-monitor: add missing Gemfile
The following error happened because we forgot to add Gemfile at
GH-135.
```
  bundle
  shell: /usr/bin/bash -e {0}
  env:
    TURBO_SITE_REPOSITORY: /home/runner/work/hotwire_ja/hotwire_ja/turbo-site
Could not locate Gemfile
Error: Process completed with exit code 10.
```